/*
 * This file is generated by jOOQ.
 */
package me.afibarra.db.tables.records;


import me.afibarra.db.tables.FilmText;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmTextRecord extends UpdatableRecordImpl<FilmTextRecord> implements Record3<UShort, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.film_text.film_id</code>.
     */
    public void setFilmId(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.film_text.film_id</code>.
     */
    public UShort getFilmId() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>sakila.film_text.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.film_text.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.film_text.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.film_text.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UShort> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UShort, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UShort, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UShort> field1() {
        return FilmText.FILM_TEXT.FILM_ID;
    }

    @Override
    public Field<String> field2() {
        return FilmText.FILM_TEXT.TITLE;
    }

    @Override
    public Field<String> field3() {
        return FilmText.FILM_TEXT.DESCRIPTION;
    }

    @Override
    public UShort component1() {
        return getFilmId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public UShort value1() {
        return getFilmId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public FilmTextRecord value1(UShort value) {
        setFilmId(value);
        return this;
    }

    @Override
    public FilmTextRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FilmTextRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FilmTextRecord values(UShort value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmTextRecord
     */
    public FilmTextRecord() {
        super(FilmText.FILM_TEXT);
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(UShort filmId, String title, String description) {
        super(FilmText.FILM_TEXT);

        setFilmId(filmId);
        setTitle(title);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
