/*
 * This file is generated by jOOQ.
 */
package me.afibarra.db.tables.records;


import java.time.LocalDateTime;

import me.afibarra.db.tables.Inventory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> implements Record4<UInteger, UShort, UByte, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.inventory.inventory_id</code>.
     */
    public void setInventoryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.inventory.inventory_id</code>.
     */
    public UInteger getInventoryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>sakila.inventory.film_id</code>.
     */
    public void setFilmId(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.inventory.film_id</code>.
     */
    public UShort getFilmId() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>sakila.inventory.store_id</code>.
     */
    public void setStoreId(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.inventory.store_id</code>.
     */
    public UByte getStoreId() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sakila.inventory.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.inventory.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, UShort, UByte, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UInteger, UShort, UByte, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Inventory.INVENTORY.INVENTORY_ID;
    }

    @Override
    public Field<UShort> field2() {
        return Inventory.INVENTORY.FILM_ID;
    }

    @Override
    public Field<UByte> field3() {
        return Inventory.INVENTORY.STORE_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Inventory.INVENTORY.LAST_UPDATE;
    }

    @Override
    public UInteger component1() {
        return getInventoryId();
    }

    @Override
    public UShort component2() {
        return getFilmId();
    }

    @Override
    public UByte component3() {
        return getStoreId();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdate();
    }

    @Override
    public UInteger value1() {
        return getInventoryId();
    }

    @Override
    public UShort value2() {
        return getFilmId();
    }

    @Override
    public UByte value3() {
        return getStoreId();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdate();
    }

    @Override
    public InventoryRecord value1(UInteger value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public InventoryRecord value2(UShort value) {
        setFilmId(value);
        return this;
    }

    @Override
    public InventoryRecord value3(UByte value) {
        setStoreId(value);
        return this;
    }

    @Override
    public InventoryRecord value4(LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public InventoryRecord values(UInteger value1, UShort value2, UByte value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(UInteger inventoryId, UShort filmId, UByte storeId, LocalDateTime lastUpdate) {
        super(Inventory.INVENTORY);

        setInventoryId(inventoryId);
        setFilmId(filmId);
        setStoreId(storeId);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }
}
