/*
 * This file is generated by jOOQ.
 */
package me.afibarra.db.tables.records;


import java.math.BigDecimal;

import me.afibarra.db.enums.NicerButSlowerFilmListRating;
import me.afibarra.db.tables.NicerButSlowerFilmList;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UShort;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NicerButSlowerFilmListRecord extends TableRecordImpl<NicerButSlowerFilmListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.FID</code>.
     */
    public void setFid(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.FID</code>.
     */
    public UShort getFid() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.length</code>.
     */
    public void setLength(UShort value) {
        set(5, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.length</code>.
     */
    public UShort getLength() {
        return (UShort) get(5);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.rating</code>.
     */
    public void setRating(NicerButSlowerFilmListRating value) {
        set(6, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.rating</code>.
     */
    public NicerButSlowerFilmListRating getRating() {
        return (NicerButSlowerFilmListRating) get(6);
    }

    /**
     * Setter for <code>sakila.nicer_but_slower_film_list.actors</code>.
     */
    public void setActors(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sakila.nicer_but_slower_film_list.actors</code>.
     */
    public String getActors() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NicerButSlowerFilmListRecord
     */
    public NicerButSlowerFilmListRecord() {
        super(NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST);
    }

    /**
     * Create a detached, initialised NicerButSlowerFilmListRecord
     */
    public NicerButSlowerFilmListRecord(UShort fid, String title, String description, String category, BigDecimal price, UShort length, NicerButSlowerFilmListRating rating, String actors) {
        super(NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST);

        setFid(fid);
        setTitle(title);
        setDescription(description);
        setCategory(category);
        setPrice(price);
        setLength(length);
        setRating(rating);
        setActors(actors);
        resetChangedOnNotNull();
    }
}
