/*
 * This file is generated by jOOQ.
 */
package me.afibarra.db.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import me.afibarra.db.tables.Payment;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> implements Record7<UShort, UShort, UByte, Integer, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.payment.payment_id</code>.
     */
    public void setPaymentId(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.payment.payment_id</code>.
     */
    public UShort getPaymentId() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>sakila.payment.customer_id</code>.
     */
    public void setCustomerId(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.payment.customer_id</code>.
     */
    public UShort getCustomerId() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>sakila.payment.staff_id</code>.
     */
    public void setStaffId(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.payment.staff_id</code>.
     */
    public UByte getStaffId() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sakila.payment.rental_id</code>.
     */
    public void setRentalId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.payment.rental_id</code>.
     */
    public Integer getRentalId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sakila.payment.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>sakila.payment.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>sakila.payment.payment_date</code>.
     */
    public void setPaymentDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sakila.payment.payment_date</code>.
     */
    public LocalDateTime getPaymentDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sakila.payment.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sakila.payment.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UShort> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UShort, UShort, UByte, Integer, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UShort, UShort, UByte, Integer, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UShort> field1() {
        return Payment.PAYMENT.PAYMENT_ID;
    }

    @Override
    public Field<UShort> field2() {
        return Payment.PAYMENT.CUSTOMER_ID;
    }

    @Override
    public Field<UByte> field3() {
        return Payment.PAYMENT.STAFF_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Payment.PAYMENT.RENTAL_ID;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Payment.PAYMENT.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Payment.PAYMENT.PAYMENT_DATE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Payment.PAYMENT.LAST_UPDATE;
    }

    @Override
    public UShort component1() {
        return getPaymentId();
    }

    @Override
    public UShort component2() {
        return getCustomerId();
    }

    @Override
    public UByte component3() {
        return getStaffId();
    }

    @Override
    public Integer component4() {
        return getRentalId();
    }

    @Override
    public BigDecimal component5() {
        return getAmount();
    }

    @Override
    public LocalDateTime component6() {
        return getPaymentDate();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdate();
    }

    @Override
    public UShort value1() {
        return getPaymentId();
    }

    @Override
    public UShort value2() {
        return getCustomerId();
    }

    @Override
    public UByte value3() {
        return getStaffId();
    }

    @Override
    public Integer value4() {
        return getRentalId();
    }

    @Override
    public BigDecimal value5() {
        return getAmount();
    }

    @Override
    public LocalDateTime value6() {
        return getPaymentDate();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdate();
    }

    @Override
    public PaymentRecord value1(UShort value) {
        setPaymentId(value);
        return this;
    }

    @Override
    public PaymentRecord value2(UShort value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public PaymentRecord value3(UByte value) {
        setStaffId(value);
        return this;
    }

    @Override
    public PaymentRecord value4(Integer value) {
        setRentalId(value);
        return this;
    }

    @Override
    public PaymentRecord value5(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public PaymentRecord value6(LocalDateTime value) {
        setPaymentDate(value);
        return this;
    }

    @Override
    public PaymentRecord value7(LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public PaymentRecord values(UShort value1, UShort value2, UByte value3, Integer value4, BigDecimal value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(UShort paymentId, UShort customerId, UByte staffId, Integer rentalId, BigDecimal amount, LocalDateTime paymentDate, LocalDateTime lastUpdate) {
        super(Payment.PAYMENT);

        setPaymentId(paymentId);
        setCustomerId(customerId);
        setStaffId(staffId);
        setRentalId(rentalId);
        setAmount(amount);
        setPaymentDate(paymentDate);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }
}
