/*
 * This file is generated by jOOQ.
 */
package me.afibarra.db.tables.records;


import java.time.LocalDateTime;

import me.afibarra.db.tables.Rental;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalRecord extends UpdatableRecordImpl<RentalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.rental.rental_id</code>.
     */
    public void setRentalId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.rental.rental_id</code>.
     */
    public Integer getRentalId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sakila.rental.rental_date</code>.
     */
    public void setRentalDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.rental.rental_date</code>.
     */
    public LocalDateTime getRentalDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sakila.rental.inventory_id</code>.
     */
    public void setInventoryId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.rental.inventory_id</code>.
     */
    public UInteger getInventoryId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>sakila.rental.customer_id</code>.
     */
    public void setCustomerId(UShort value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.rental.customer_id</code>.
     */
    public UShort getCustomerId() {
        return (UShort) get(3);
    }

    /**
     * Setter for <code>sakila.rental.return_date</code>.
     */
    public void setReturnDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>sakila.rental.return_date</code>.
     */
    public LocalDateTime getReturnDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sakila.rental.staff_id</code>.
     */
    public void setStaffId(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>sakila.rental.staff_id</code>.
     */
    public UByte getStaffId() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>sakila.rental.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sakila.rental.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RentalRecord
     */
    public RentalRecord() {
        super(Rental.RENTAL);
    }

    /**
     * Create a detached, initialised RentalRecord
     */
    public RentalRecord(Integer rentalId, LocalDateTime rentalDate, UInteger inventoryId, UShort customerId, LocalDateTime returnDate, UByte staffId, LocalDateTime lastUpdate) {
        super(Rental.RENTAL);

        setRentalId(rentalId);
        setRentalDate(rentalDate);
        setInventoryId(inventoryId);
        setCustomerId(customerId);
        setReturnDate(returnDate);
        setStaffId(staffId);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }
}
