/*
 * This file is generated by jOOQ.
 */
package me.afibarra.db.tables.records;


import java.math.BigDecimal;

import me.afibarra.db.tables.SalesByStore;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesByStoreRecord extends TableRecordImpl<SalesByStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.sales_by_store.store</code>.
     */
    public void setStore(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.sales_by_store.store</code>.
     */
    public String getStore() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sakila.sales_by_store.manager</code>.
     */
    public void setManager(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.sales_by_store.manager</code>.
     */
    public String getManager() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.sales_by_store.total_sales</code>.
     */
    public void setTotalSales(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.sales_by_store.total_sales</code>.
     */
    public BigDecimal getTotalSales() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesByStoreRecord
     */
    public SalesByStoreRecord() {
        super(SalesByStore.SALES_BY_STORE);
    }

    /**
     * Create a detached, initialised SalesByStoreRecord
     */
    public SalesByStoreRecord(String store, String manager, BigDecimal totalSales) {
        super(SalesByStore.SALES_BY_STORE);

        setStore(store);
        setManager(manager);
        setTotalSales(totalSales);
        resetChangedOnNotNull();
    }
}
